### ISSUE TITLE
Unable to share Trebleshot app.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [genonbeta/TrebleShot#48] opened 2018-04-08 07:50 UTC
#### Expected behaviour
After downloading the app ,i tried to share the app by its own feature, it must be able to share .

#### Actual behavior
After opening the app, want to share the app by its own feature available in its toolbar by sliding it from left to right. It is not working. 

#### How to reproduce
Install app from f droid

Open the app

Slide screen from left to right to open its toolbar. 

Scroll down to see share this app feature. 

Click on it to reproduce the bug. 

* Browser: Trebleshot
* Version:1.2.5.12
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/nKiZ1ePxq6k
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/unable-to-share-trebleshot-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by velitasali** [comment] 2018-04-29 11:33
I could not reproduce the issue on Android 5.1.1 with version 1.2.6.1-DEBUG. 

Please let me know if the issue is fixed with the new version or if it is device specific, then I might also need the logs occurring when you click that button.

Thanks.

**Closed** 2019-04-12 09:18 UTC
Labels: bug, wontfix
