### ISSUE TITLE
TrebleShot stopped While Click on Image folder. 

### ISSUE THREAD

**Issue by wanizubair** [genonbeta/TrebleShot#32] opened 2018-02-17 19:52 UTC
#### Expected behavior
The app should be able to open image folder. 

#### Actual behavior
The app is not able to share images as the image folder does not open in TrebleShot. 

#### How to reproduce

+ Launch the app. 

+ Click on the menu icon left at the top corner of app, you see different options there. 

+ Click on the image icon. 

+ You would not able to share image as the image icon does not work, TrebleShot crashes and app does not work. 

* Browser: TrebleShot 

* Operating system:Android 7.0 (Nought) 

#### Recording Of The Bug
https://youtu.be/CvtnEEcHeWs    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wanizubair/trebleshot-stopped-while-click-on-image-folder">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by velitasali** [comment] 2018-02-20 14:49
Committed changes for the issue. Please let me know if the problem is fixed when I release the new version

**Comment by velitasali** [comment] 2018-02-23 17:25
@wanizubair Could you approve that the issues is fixed? Thanks.

**Closed** 2019-04-12 09:53 UTC
Labels: bug, ✓done
