### ISSUE TITLE
"Device name" does not always get updated in "Device list"

### ISSUE THREAD

**Issue by ElTopo** [genonbeta/TrebleShot#45] opened 2018-03-29 18:56 UTC
Hello,

I have several amazon fire tablets (same model), so I changed their "Device name" to be different from each other in Preference. The changed name shows up locally (next to the version and the green icon), however, other devices still see the old name even after I refresh the device list.

So far, my phone (Android 7) is the only one that successfully updates its name in the device list; my other Android 4 and Android 5 phones/tablets still have their old names displayed in the device list.

TrebleShot version: 1.2.5.12, installed from Google Play Store.

**Comment by ElTopo** [comment] 2018-03-29 22:01
@velitasali Thanks for the reply. I tried "force stop" and it indeed fixes the device names in the list.

**Comment by velitasali** [comment] 2018-04-18 20:42
Hi @ElTopo ,

With latest release the issue is addressed and fixed. Please let me know if it is now working as intended, so that we can close the issue,

Thanks.

**Comment by ElTopo** [comment] 2018-04-19 00:33
@velitasali Just got the latest release (1.2.6) from Google Play Store, and I verified that this issue has been properly addressed.

Thanks for a great job!

**Closed** 2018-04-19 00:34 UTC
Labels: bug
